services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "100.116.224.88:80:80"
      - "100.116.224.88:443:443"
      - "100.116.224.88:443:443/udp"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - gateway_net

volumes:
  caddy_data:
  caddy_config:

networks:
  gateway_net:
    external: true

